# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'FOMO' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FOMO
    pod 'QR-Code-Encoder-for-Objective-C'
    pod 'QRCodeReaderViewController'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
	

  target 'FOMOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FOMOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
